### ISSUE TITLE
Panel Meter Specs

### ISSUE THREAD

**Issue by Andrew-Hanlon** [mstratman/vu-meter-driver#1]
Thanks for the great pedal add on - I have ordered a couple of the kits!

Can you add some additional detail around the required Panel Meter specs? I am assuming it is a DC volt meter, but in what range is usable? Thanks!

**Comment by mstratman** [comment]
Yes a DC volt meter. I'm going to guess any meter will work with it. (within a reasonable range of your power supply)

That said, I'll try to measure or calculate its range later for the values listed in the schematic. However even if you got a meter that was hard to dial in, you can pretty easily switch the gain with component swaps, or change the sensitivity of the RV pot/trimmer.

**Comment by Andrew-Hanlon** [comment]
Thanks @mstratman for the information and I would certainly appreciate the additional info for the OOTB sensitivity range.

**Comment by mstratman** [comment]
I did a quick and dirty test and was getting it to go up to about 3V.

**Comment by Andrew-Hanlon** [comment]
Thanks kindly @mstratman . I guess that makes sense - basically the meter's range should be below the approximate half rail voltage (4.5v) and then adjust the gain to suit. Cheers.

**Comment by mstratman** [comment]
Yeah, exactly. To be clear that was with a 9V supply.
