### ISSUE TITLE
Meter doesnt retun to zero.

### ISSUE THREAD

**Issue by The4gotn1** [mstratman/vu-meter-driver#2]
Ordered your kit and components.  I finished the build and when powered on the meter is already half way up.  It then moves when I send a signal through it amd returns to half way up.  Only when I pull the power does it return to 0.

Any ideas?

**Comment by mstratman** [comment]
Try measuring your voltage at the d1 d2 intersection. Also at the input of the entire board.

Closing since it's not an issue with the project but your build. Happy to continue helping troubleshoot though, but I'll have limited ability until Tues when I'm back in my office

**Comment by The4gotn1** [comment]
I get 3.04 v on the D1 leg closest to the edge of the board.  But I get 0 on the D2 leg closest to the edge of the board.

________________________________

**Comment by The4gotn1** [comment]
Sorry wrong pins. I get .263v on both.

________________________________
